/**
 * OpenStreetMap から大阪大学各キャンパスの建物（名称・座標）を取得し、
 * 冪等な SQL シード（lib/db/seed/osm_buildings.sql）を生成する開発用スクリプト。
 *
 * 実行時に Overpass API を叩くため、ランタイム（Workers）からは使わない。建物名
 * ラベルは buildings テーブルから配信する方針なので、これは一度きりの ETL。
 *
 * 使い方:
 *   node node_modules/tsx/dist/cli.mjs scripts/fetch-osm-buildings.ts
 *   その後 lib/db/seed/osm_buildings.sql を dev リモート D1 に適用する。
 *
 * キャンパス割り当て:
 *   - 豊中 / 吹田: OSM の amenity=university エリアポリゴン内の建物を抽出。
 *   - 箕面: 新キャンパス（箕面船場）は OSM 上で単一の複合棟「大阪大学 箕面キャンパス」
 *     としてのみ登録されており、周辺の商業ビルと混在する bbox では絞れないため、
 *     名称に「大阪大学」を含む建物のみ採用する。
 */
import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OVERPASS_URL = 'https://overpass-api.de/api/interpreter';

// OSM の amenity=university エリア（way）ID。area ID = 2_400_000_000 + way ID。
const TOYONAKA_WAY = 508305218;
const SUITA_WAY = 237968488;
// 箕面新キャンパス（船場）の探索 bbox。商業ビルが混じるため後段で名称フィルタする。
const MINOH_BBOX = '34.8190,135.4870,34.8270,135.4960';

type CampusId = 'toyonaka' | 'suita' | 'minoh';

interface OverpassElement {
  type: string;
  id: number;
  center?: { lat: number; lon: number };
  lat?: number;
  lon?: number;
  tags?: Record<string, string>;
}

interface BuildingRow {
  id: string;
  campusId: CampusId;
  name: string;
  latitude: number;
  longitude: number;
}

const QUERY = `
[out:json][timeout:120];
way(${TOYONAKA_WAY}); map_to_area->.toyoA;
way(${SUITA_WAY}); map_to_area->.suitaA;
( way["building"]["name"](area.toyoA); )->.toyo;
( way["building"]["name"](area.suitaA); )->.suita;
( way["building"]["name"](${MINOH_BBOX}); )->.minoh;
.toyo out tags center;
.suita out tags center;
.minoh out tags center;
`;

/** 全角英数字・全角スペースを半角化し、空白を整理する。 */
function normalizeName(raw: string): string {
  const halfWidth = raw.replace(/[！-～]/g, (ch) =>
    String.fromCharCode(ch.charCodeAt(0) - 0xfee0)
  );
  return (
    halfWidth
      .replace(/　/g, ' ')
      .replace(/\s+/g, ' ')
      .trim()
      // 末尾の ASCII のみの括弧書き（ローマ字訳）を除去。例: 「待兼山会館 (Machikaneyama Facility)」
      // → 「待兼山会館」。中身に非 ASCII を含む括弧（例: 「(Σホール)」）は残す。
      .replace(/\s*\([\x20-\x7E]+\)\s*$/, '')
      .trim()
  );
}

const CAMPUS_CENTERS: Record<CampusId, [number, number]> = {
  toyonaka: [34.804, 135.456],
  suita: [34.822, 135.525],
  minoh: [34.823, 135.4915],
};

function haversineMeters(
  [lat1, lng1]: [number, number],
  [lat2, lng2]: [number, number]
): number {
  const R = 6_371_000;
  const r = (x: number) => (x * Math.PI) / 180;
  const dLat = r(lat2 - lat1);
  const dLng = r(lng2 - lng1);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(r(lat1)) * Math.cos(r(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

/** 最寄りのキャンパス中心でキャンパスを判定する（豊中/吹田の振り分け用）。 */
function nearestCampus(lat: number, lng: number): CampusId {
  let best: CampusId = 'toyonaka';
  let bestDist = Infinity;
  for (const id of Object.keys(CAMPUS_CENTERS) as CampusId[]) {
    const d = haversineMeters([lat, lng], CAMPUS_CENTERS[id]);
    if (d < bestDist) {
      bestDist = d;
      best = id;
    }
  }
  return best;
}

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

async function main() {
  const res = await fetch(OVERPASS_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'carrymybottle-osm-building-seed/1.0',
    },
    body: new URLSearchParams({ data: QUERY }),
  });
  if (!res.ok) {
    throw new Error(`Overpass request failed: ${res.status}`);
  }
  const data = (await res.json()) as { elements: OverpassElement[] };

  const seen = new Set<string>(); // `${campus}::${name}` で campus 内の重複名を排除
  const rows: BuildingRow[] = [];

  for (const el of data.elements) {
    const center =
      el.center ?? (el.lat && el.lon ? { lat: el.lat, lon: el.lon } : null);
    const rawName = el.tags?.name;
    if (!center || !rawName) continue;

    const name = normalizeName(rawName);
    if (!name) continue;

    const campusId = nearestCampus(center.lat, center.lon);

    // 箕面は新キャンパスの建物（名称に「大阪大学」を含む）のみ採用する。
    if (campusId === 'minoh' && !name.includes('大阪大学')) continue;

    const dedupeKey = `${campusId}::${name}`;
    if (seen.has(dedupeKey)) continue;
    seen.add(dedupeKey);

    rows.push({
      id: `${campusId}_osm_${el.id}`,
      campusId,
      name,
      latitude: Math.round(center.lat * 1e6) / 1e6,
      longitude: Math.round(center.lon * 1e6) / 1e6,
    });
  }

  rows.sort((a, b) =>
    a.campusId === b.campusId
      ? a.name.localeCompare(b.name, 'ja')
      : a.campusId.localeCompare(b.campusId)
  );

  const counts = rows.reduce<Record<string, number>>((acc, r) => {
    acc[r.campusId] = (acc[r.campusId] ?? 0) + 1;
    return acc;
  }, {});

  const header = `-- OSM-derived building seed (idempotent). Generated by scripts/fetch-osm-buildings.ts.
-- Source: OpenStreetMap via Overpass API. © OpenStreetMap contributors (ODbL).
-- Run: wrangler d1 execute DB --remote --file=lib/db/seed/osm_buildings.sql
-- Counts: ${JSON.stringify(counts)}
-- INSERT OR IGNORE keeps existing rows (and the unique(campus_id, name) index
-- prevents name collisions with legacy seeds); the UPDATE refreshes coordinates
-- for OSM-sourced rows so re-running stays safe and converges.

`;

  // 建物の FK（campus_id -> campuses.id）を満たすため、キャンパス行も冪等に投入する。
  // dev リモート D1 には minoh が未投入のことがあるため、ここで担保する。
  const campusSeed = `INSERT OR IGNORE INTO campuses (id, name, map_image_path, created_at, updated_at)
VALUES
  ('toyonaka', '豊中', '/maps/toyonaka.png', strftime('%s','now'), strftime('%s','now')),
  ('suita',    '吹田', '/maps/suita.png',    strftime('%s','now'), strftime('%s','now')),
  ('minoh',    '箕面', '/maps/minoh.png',    strftime('%s','now'), strftime('%s','now'));

`;

  const insertValues = rows
    .map(
      (r) =>
        `  (${sqlString(r.id)}, ${sqlString(r.campusId)}, ${sqlString(r.name)}, 0, ${r.latitude}, ${r.longitude}, strftime('%s','now'), strftime('%s','now'))`
    )
    .join(',\n');

  const updates = rows
    .map(
      (r) =>
        `UPDATE buildings SET latitude = ${r.latitude}, longitude = ${r.longitude} WHERE id = ${sqlString(r.id)};`
    )
    .join('\n');

  const sql = `${header}${campusSeed}INSERT OR IGNORE INTO buildings (id, campus_id, name, sort_order, latitude, longitude, created_at, updated_at)
VALUES
${insertValues};

${updates}
`;

  const outPath = join(process.cwd(), 'lib/db/seed/osm_buildings.sql');
  await writeFile(outPath, sql, 'utf8');
  console.log(`Wrote ${rows.length} buildings -> ${outPath}`);
  console.log('Counts:', counts);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
