-- OSM-derived building seed (idempotent). Generated by scripts/fetch-osm-buildings.ts.
-- Source: OpenStreetMap via Overpass API. © OpenStreetMap contributors (ODbL).
-- Run: wrangler d1 execute DB --remote --file=lib/db/seed/osm_buildings.sql
-- Counts: {"minoh":1,"suita":128,"toyonaka":44}
-- INSERT OR IGNORE keeps existing rows (and the unique(campus_id, name) index
-- prevents name collisions with legacy seeds); the UPDATE refreshes coordinates
-- for OSM-sourced rows so re-running stays safe and converges.

INSERT OR IGNORE INTO campuses (id, name, map_image_path, created_at, updated_at)
VALUES
  ('toyonaka', '豊中', '/maps/toyonaka.png', strftime('%s','now'), strftime('%s','now')),
  ('suita',    '吹田', '/maps/suita.png',    strftime('%s','now'), strftime('%s','now')),
  ('minoh',    '箕面', '/maps/minoh.png',    strftime('%s','now'), strftime('%s','now'));

INSERT OR IGNORE INTO buildings (id, campus_id, name, sort_order, latitude, longitude, created_at, updated_at)
VALUES
  ('minoh_osm_986891121', 'minoh', '大阪大学 箕面キャンパス', 0, 34.822852, 135.491474, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254578', 'suita', '21世紀プラザ', 0, 34.82103, 135.52493, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254308', 'suita', 'A1棟', 0, 34.824032, 135.523945, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254560', 'suita', 'A2棟', 0, 34.824238, 135.524077, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258252', 'suita', 'C1棟', 0, 34.823488, 135.520596, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258255', 'suita', 'C2棟', 0, 34.823599, 135.52017, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258254', 'suita', 'C3棟', 0, 34.82382, 135.520086, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258251', 'suita', 'C4棟', 0, 34.823675, 135.520677, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258250', 'suita', 'C5棟', 0, 34.82388, 135.520786, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378255249', 'suita', 'C6棟', 0, 34.82413, 135.52099, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258249', 'suita', 'C7棟', 0, 34.824311, 135.521135, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258245', 'suita', 'C8棟', 0, 34.823974, 135.521275, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254019', 'suita', 'E1棟', 0, 34.822761, 135.522508, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254295', 'suita', 'E2棟', 0, 34.823033, 135.522668, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254296', 'suita', 'E3棟', 0, 34.823238, 135.522751, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254297', 'suita', 'E4棟', 0, 34.823423, 135.522868, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254298', 'suita', 'E5棟', 0, 34.823632, 135.522972, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254299', 'suita', 'E6棟', 0, 34.823823, 135.523064, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258243', 'suita', 'F1棟', 0, 34.823934, 135.521771, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258244', 'suita', 'F2棟', 0, 34.824015, 135.521534, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996295', 'suita', 'IFReC動物実験棟', 0, 34.824958, 135.519337, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_602602540', 'suita', 'M1棟', 0, 34.822278, 135.521719, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_602602529', 'suita', 'M3棟', 0, 34.822114, 135.521295, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254303', 'suita', 'P1棟', 0, 34.822767, 135.523061, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254302', 'suita', 'P2棟', 0, 34.822845, 135.523366, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258246', 'suita', 'R4棟', 0, 34.824337, 135.521579, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258247', 'suita', 'R5棟', 0, 34.82422, 135.521982, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996303', 'suita', 'RI総合センター新館', 0, 34.819775, 135.525312, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403006523', 'suita', 'RI総合センター本館', 0, 34.819919, 135.52552, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254107', 'suita', 'S1棟', 0, 34.822074, 135.522317, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378255686', 'suita', 'S2棟', 0, 34.82173, 135.522191, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254550', 'suita', 'S3棟', 0, 34.821491, 135.524499, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258257', 'suita', 'U1E棟', 0, 34.823026, 135.520753, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258259', 'suita', 'U1M棟', 0, 34.823136, 135.52045, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258258', 'suita', 'U1W棟', 0, 34.823243, 135.520138, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258256', 'suita', 'U2棟', 0, 34.822808, 135.521536, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254504', 'suita', 'U3棟', 0, 34.82261, 135.52196, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254304', 'suita', 'U4棟', 0, 34.823115, 135.523318, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378255688', 'suita', 'U5棟', 0, 34.821454, 135.521529, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254551', 'suita', 'U6棟', 0, 34.821183, 135.524511, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254549', 'suita', 'U7棟', 0, 34.821343, 135.523964, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254512', 'suita', 'U8棟', 0, 34.821443, 135.523718, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254301', 'suita', 'U93棟', 0, 34.823715, 135.522713, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254579', 'suita', 'US1棟', 0, 34.821123, 135.523492, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996267', 'suita', 'カフェテリア匠', 0, 34.818148, 135.523766, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379514489', 'suita', 'コンベンションセンター', 0, 34.817881, 135.522586, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_435093454', 'suita', 'サイバーメディアセンター', 0, 34.821711, 135.527035, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254567', 'suita', 'サイバーメディアセンター 吹田教育実習棟', 0, 34.820854, 135.525865, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254564', 'suita', 'サイバーメディアセンター 本館', 0, 34.822332, 135.526515, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379513536', 'suita', 'スマートプロセス研究センター1号館', 0, 34.824994, 135.525796, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379513544', 'suita', 'スマートプロセス研究センター2号館', 0, 34.824684, 135.525955, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379514490', 'suita', 'たけのこ保育園', 0, 34.819322, 135.522203, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378255690', 'suita', 'テクノアライアンス棟', 0, 34.820954, 135.522624, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379515971', 'suita', 'ナノテクノロジー総合研究棟', 0, 34.825763, 135.523536, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254307', 'suita', 'フォトニクスセンター・P3棟', 0, 34.822677, 135.523632, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996277', 'suita', 'ポプラ通り福利会館', 0, 34.818527, 135.522035, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_446898812', 'suita', 'まきば保育園', 0, 34.821418, 135.527099, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378412322', 'suita', 'レーザーエネルギー学研究センター', 0, 34.820484, 135.524279, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996271', 'suita', '医学部', 0, 34.819342, 135.526798, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996284', 'suita', '医学部付属病院', 0, 34.819343, 135.52832, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379514193', 'suita', '医学部保健学科/医学系研究科保健学専攻', 0, 34.818151, 135.520616, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403002079', 'suita', '核物理研AVFサイクロトロン棟', 0, 34.826067, 135.527761, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379513552', 'suita', '核物理研リングサイクロトロン棟', 0, 34.82665, 135.527209, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379513540', 'suita', '核物理研本館', 0, 34.825942, 135.526799, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996302', 'suita', '環境安全研究管理センター', 0, 34.819707, 135.524863, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378412320', 'suita', '銀杏会館', 0, 34.820904, 135.526716, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996287', 'suita', '工学AR棟', 0, 34.822964, 135.524099, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403001239', 'suita', '工学低温実験棟', 0, 34.825284, 135.522958, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258114', 'suita', '工学部/工学研究科 A12棟', 0, 34.825474, 135.525153, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258112', 'suita', '工学部/工学研究科 A13棟', 0, 34.825719, 135.525833, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258109', 'suita', '工学部/工学研究科 A14棟', 0, 34.825873, 135.525023, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258107', 'suita', '工学部/工学研究科 A15棟', 0, 34.826093, 135.525544, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378255248', 'suita', '工学部/工学研究科 R1棟', 0, 34.823212, 135.521295, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378255247', 'suita', '工学部/工学研究科 R2棟', 0, 34.823415, 135.521417, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258242', 'suita', '工学部/工学研究科 R3棟', 0, 34.823625, 135.521532, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379513534', 'suita', '荒田記念館', 0, 34.825158, 135.525777, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996289', 'suita', '産学共創A棟', 0, 34.822973, 135.525016, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996288', 'suita', '産学共創B棟', 0, 34.823205, 135.524757, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996286', 'suita', '産学共創C棟', 0, 34.823361, 135.524287, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254306', 'suita', '産学共創D棟', 0, 34.823522, 135.523883, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403001285', 'suita', '産研コバルト棟', 0, 34.824547, 135.524419, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996297', 'suita', '産研ライナック棟', 0, 34.82473, 135.524621, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403001174', 'suita', '産研管理棟', 0, 34.824499, 135.523421, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996300', 'suita', '産研総合解析センター', 0, 34.825092, 135.522289, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996298', 'suita', '産研第2研究棟', 0, 34.825516, 135.52341, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254559', 'suita', '産研第一研究棟', 0, 34.824794, 135.523385, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996301', 'suita', '産研電子プロセス実験棟', 0, 34.825368, 135.522472, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996263', 'suita', '歯学部/歯学研究科', 0, 34.819349, 135.521503, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996265', 'suita', '歯学部付属病院', 0, 34.819563, 135.520968, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403006524', 'suita', '社研A棟', 0, 34.822941, 135.525756, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254565', 'suita', '社研B棟', 0, 34.823139, 135.525604, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996260', 'suita', '情報科学研究科A棟', 0, 34.818267, 135.522288, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996261', 'suita', '情報科学研究科B棟', 0, 34.818003, 135.521749, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996262', 'suita', '情報科学研究科C棟', 0, 34.818438, 135.52162, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258248', 'suita', '職員会館', 0, 34.824754, 135.521721, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_446898800', 'suita', '人間科学部・人間科学研究科', 0, 34.817818, 135.525918, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378255691', 'suita', '吹田福利会館', 0, 34.823284, 135.522076, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378258253', 'suita', '生物工学国際交流センター', 0, 34.824095, 135.520214, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379514187', 'suita', '生命科学図書館', 0, 34.818957, 135.525729, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996282', 'suita', '生命機能研究科 ES棟', 0, 34.817206, 135.527838, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996283', 'suita', '生命機能研究科 ナノバイオロジー棟', 0, 34.817408, 135.528364, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996280', 'suita', '生命機能研究科 細胞棟', 0, 34.817496, 135.52751, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996281', 'suita', '生命機能研究科 生命システム棟', 0, 34.817067, 135.52729, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379513538', 'suita', '接合科学研究所', 0, 34.825204, 135.526388, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379513542', 'suita', '接合研実験棟', 0, 34.824948, 135.526711, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254214', 'suita', '体育館', 0, 34.817592, 135.523132, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_505704346', 'suita', '大阪大学 国際交流会館吹田分館', 0, 34.824431, 135.51829, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996264', 'suita', '大阪大学歯学部', 0, 34.818831, 135.521164, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996266', 'suita', '大阪大学本部', 0, 34.818698, 135.523905, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403002811', 'suita', '蛋白研NMR実験棟', 0, 34.825492, 135.519652, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379516456', 'suita', '蛋白研共同研究拠点', 0, 34.825736, 135.520139, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379516459', 'suita', '蛋白研構造解析研究棟', 0, 34.825338, 135.519383, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379516457', 'suita', '蛋白研分析実験棟', 0, 34.825577, 135.520423, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_379516458', 'suita', '蛋白質研究所', 0, 34.825332, 135.520121, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378255936', 'suita', '中央機械棟', 0, 34.823838, 135.522364, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254561', 'suita', '超高圧電子顕微鏡センター', 0, 34.823716, 135.52508, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403006709', 'suita', '超電導フォトニクス実験棟', 0, 34.823328, 135.523858, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254305', 'suita', '低温センター', 0, 34.823367, 135.523532, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996268', 'suita', '電子顕微鏡センター', 0, 34.81875, 135.523147, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996299', 'suita', '楠本会館', 0, 34.825337, 135.521598, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403003008', 'suita', '微研南館', 0, 34.823801, 135.519441, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996294', 'suita', '微研北館', 0, 34.825144, 135.518876, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996291', 'suita', '微研本館', 0, 34.824124, 135.519157, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378254566', 'suita', '保健センター 吹田分室', 0, 34.821277, 135.52548, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996305', 'suita', '本部前福利会館', 0, 34.819227, 135.524766, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996293', 'suita', '免疫学フロンティア研究センター', 0, 34.824805, 135.519897, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_389996274', 'suita', '薬学部/薬学研究科', 0, 34.817065, 135.520699, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_403003007', 'suita', '融合型生命科学総合研究棟', 0, 34.824406, 135.519771, strftime('%s','now'), strftime('%s','now')),
  ('suita_osm_378253856', 'suita', '理工学図書館', 0, 34.822189, 135.523098, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_225710187', 'toyonaka', 'グローバルコラボレーションセンター', 0, 34.806442, 135.453897, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_220488371', 'toyonaka', 'サイバーメディアセンター', 0, 34.805051, 135.455962, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_462745564', 'toyonaka', 'まちかね保育園', 0, 34.804576, 135.456808, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_158629518', 'toyonaka', 'らふぉれ', 0, 34.803399, 135.453931, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_498412575', 'toyonaka', 'ルネクール・ムラタ', 0, 34.807522, 135.45494, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157287063', 'toyonaka', '学生交流棟', 0, 34.805687, 135.45275, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_84971080', 'toyonaka', '基礎工学部G棟', 0, 34.803374, 135.45691, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_84971156', 'toyonaka', '基礎工学部J棟', 0, 34.803219, 135.456283, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_229128016', 'toyonaka', '基礎工学部国際棟 (Σホール)', 0, 34.803435, 135.455335, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_225710189', 'toyonaka', '共通教育A棟', 0, 34.806164, 135.454339, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_225710190', 'toyonaka', '共通教育B棟', 0, 34.805899, 135.454865, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_225710191', 'toyonaka', '共通教育C棟', 0, 34.806413, 135.45472, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_463870353', 'toyonaka', '健康体育研究棟', 0, 34.807107, 135.456037, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_158629520', 'toyonaka', '言語文化研究科', 0, 34.805466, 135.453569, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_225705867', 'toyonaka', '実験棟', 0, 34.806334, 135.453491, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_225710186', 'toyonaka', '総合学術博物館', 0, 34.807422, 135.449044, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157098221', 'toyonaka', '総合図書館', 0, 34.804954, 135.45507, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_463870354', 'toyonaka', '多目的倉庫', 0, 34.8069, 135.455699, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_311504482', 'toyonaka', '体育館', 0, 34.807009, 135.455258, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_229130610', 'toyonaka', '待兼山会館', 0, 34.805111, 135.452112, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_463870348', 'toyonaka', '大講義棟', 0, 34.805716, 135.455191, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_225710182', 'toyonaka', '大阪大学会館', 0, 34.806669, 135.452583, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157105371', 'toyonaka', '大阪大学国際交流会館', 0, 34.805204, 135.457177, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157119834', 'toyonaka', '大阪大学生協', 0, 34.804461, 135.452863, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_463870352', 'toyonaka', '第二体育館', 0, 34.80723, 135.455779, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_229237337', 'toyonaka', '中庭会議室', 0, 34.804744, 135.454427, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157302297', 'toyonaka', '日本学棟', 0, 34.804859, 135.453402, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157294755', 'toyonaka', '美学棟', 0, 34.80468, 135.453696, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157294754', 'toyonaka', '文法経講義棟', 0, 34.805107, 135.453469, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157146925', 'toyonaka', '文法経本館', 0, 34.804738, 135.454463, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_157294753', 'toyonaka', '法経講義棟', 0, 34.805013, 135.453788, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_311504481', 'toyonaka', '豊中共創棟A', 0, 34.802853, 135.456244, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_1525493177', 'toyonaka', '豊中共創棟B', 0, 34.802932, 135.455897, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_229126801', 'toyonaka', '豊中総合学館', 0, 34.80428, 135.453748, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_383575495', 'toyonaka', '明道館', 0, 34.804575, 135.452525, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_461654531', 'toyonaka', '理学部A棟', 0, 34.802603, 135.454957, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_461654532', 'toyonaka', '理学部B棟', 0, 34.802662, 135.455635, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_461654533', 'toyonaka', '理学部C棟', 0, 34.802263, 135.455476, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_461654535', 'toyonaka', '理学部D棟', 0, 34.802453, 135.455605, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_461654534', 'toyonaka', '理学部E棟', 0, 34.802401, 135.45625, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_231162027', 'toyonaka', '理学部F棟', 0, 34.801731, 135.45511, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_231162028', 'toyonaka', '理学部G棟', 0, 34.801829, 135.455571, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_461654530', 'toyonaka', '理学部H棟', 0, 34.802102, 135.455092, strftime('%s','now'), strftime('%s','now')),
  ('toyonaka_osm_486946397', 'toyonaka', '理学部J棟', 0, 34.80298, 135.455668, strftime('%s','now'), strftime('%s','now'));

UPDATE buildings SET name = '大阪大学 箕面キャンパス', latitude = 34.822852, longitude = 135.491474 WHERE id = 'minoh_osm_986891121';
UPDATE buildings SET name = '21世紀プラザ', latitude = 34.82103, longitude = 135.52493 WHERE id = 'suita_osm_378254578';
UPDATE buildings SET name = 'A1棟', latitude = 34.824032, longitude = 135.523945 WHERE id = 'suita_osm_378254308';
UPDATE buildings SET name = 'A2棟', latitude = 34.824238, longitude = 135.524077 WHERE id = 'suita_osm_378254560';
UPDATE buildings SET name = 'C1棟', latitude = 34.823488, longitude = 135.520596 WHERE id = 'suita_osm_378258252';
UPDATE buildings SET name = 'C2棟', latitude = 34.823599, longitude = 135.52017 WHERE id = 'suita_osm_378258255';
UPDATE buildings SET name = 'C3棟', latitude = 34.82382, longitude = 135.520086 WHERE id = 'suita_osm_378258254';
UPDATE buildings SET name = 'C4棟', latitude = 34.823675, longitude = 135.520677 WHERE id = 'suita_osm_378258251';
UPDATE buildings SET name = 'C5棟', latitude = 34.82388, longitude = 135.520786 WHERE id = 'suita_osm_378258250';
UPDATE buildings SET name = 'C6棟', latitude = 34.82413, longitude = 135.52099 WHERE id = 'suita_osm_378255249';
UPDATE buildings SET name = 'C7棟', latitude = 34.824311, longitude = 135.521135 WHERE id = 'suita_osm_378258249';
UPDATE buildings SET name = 'C8棟', latitude = 34.823974, longitude = 135.521275 WHERE id = 'suita_osm_378258245';
UPDATE buildings SET name = 'E1棟', latitude = 34.822761, longitude = 135.522508 WHERE id = 'suita_osm_378254019';
UPDATE buildings SET name = 'E2棟', latitude = 34.823033, longitude = 135.522668 WHERE id = 'suita_osm_378254295';
UPDATE buildings SET name = 'E3棟', latitude = 34.823238, longitude = 135.522751 WHERE id = 'suita_osm_378254296';
UPDATE buildings SET name = 'E4棟', latitude = 34.823423, longitude = 135.522868 WHERE id = 'suita_osm_378254297';
UPDATE buildings SET name = 'E5棟', latitude = 34.823632, longitude = 135.522972 WHERE id = 'suita_osm_378254298';
UPDATE buildings SET name = 'E6棟', latitude = 34.823823, longitude = 135.523064 WHERE id = 'suita_osm_378254299';
UPDATE buildings SET name = 'F1棟', latitude = 34.823934, longitude = 135.521771 WHERE id = 'suita_osm_378258243';
UPDATE buildings SET name = 'F2棟', latitude = 34.824015, longitude = 135.521534 WHERE id = 'suita_osm_378258244';
UPDATE buildings SET name = 'IFReC動物実験棟', latitude = 34.824958, longitude = 135.519337 WHERE id = 'suita_osm_389996295';
UPDATE buildings SET name = 'M1棟', latitude = 34.822278, longitude = 135.521719 WHERE id = 'suita_osm_602602540';
UPDATE buildings SET name = 'M3棟', latitude = 34.822114, longitude = 135.521295 WHERE id = 'suita_osm_602602529';
UPDATE buildings SET name = 'P1棟', latitude = 34.822767, longitude = 135.523061 WHERE id = 'suita_osm_378254303';
UPDATE buildings SET name = 'P2棟', latitude = 34.822845, longitude = 135.523366 WHERE id = 'suita_osm_378254302';
UPDATE buildings SET name = 'R4棟', latitude = 34.824337, longitude = 135.521579 WHERE id = 'suita_osm_378258246';
UPDATE buildings SET name = 'R5棟', latitude = 34.82422, longitude = 135.521982 WHERE id = 'suita_osm_378258247';
UPDATE buildings SET name = 'RI総合センター新館', latitude = 34.819775, longitude = 135.525312 WHERE id = 'suita_osm_389996303';
UPDATE buildings SET name = 'RI総合センター本館', latitude = 34.819919, longitude = 135.52552 WHERE id = 'suita_osm_403006523';
UPDATE buildings SET name = 'S1棟', latitude = 34.822074, longitude = 135.522317 WHERE id = 'suita_osm_378254107';
UPDATE buildings SET name = 'S2棟', latitude = 34.82173, longitude = 135.522191 WHERE id = 'suita_osm_378255686';
UPDATE buildings SET name = 'S3棟', latitude = 34.821491, longitude = 135.524499 WHERE id = 'suita_osm_378254550';
UPDATE buildings SET name = 'U1E棟', latitude = 34.823026, longitude = 135.520753 WHERE id = 'suita_osm_378258257';
UPDATE buildings SET name = 'U1M棟', latitude = 34.823136, longitude = 135.52045 WHERE id = 'suita_osm_378258259';
UPDATE buildings SET name = 'U1W棟', latitude = 34.823243, longitude = 135.520138 WHERE id = 'suita_osm_378258258';
UPDATE buildings SET name = 'U2棟', latitude = 34.822808, longitude = 135.521536 WHERE id = 'suita_osm_378258256';
UPDATE buildings SET name = 'U3棟', latitude = 34.82261, longitude = 135.52196 WHERE id = 'suita_osm_378254504';
UPDATE buildings SET name = 'U4棟', latitude = 34.823115, longitude = 135.523318 WHERE id = 'suita_osm_378254304';
UPDATE buildings SET name = 'U5棟', latitude = 34.821454, longitude = 135.521529 WHERE id = 'suita_osm_378255688';
UPDATE buildings SET name = 'U6棟', latitude = 34.821183, longitude = 135.524511 WHERE id = 'suita_osm_378254551';
UPDATE buildings SET name = 'U7棟', latitude = 34.821343, longitude = 135.523964 WHERE id = 'suita_osm_378254549';
UPDATE buildings SET name = 'U8棟', latitude = 34.821443, longitude = 135.523718 WHERE id = 'suita_osm_378254512';
UPDATE buildings SET name = 'U93棟', latitude = 34.823715, longitude = 135.522713 WHERE id = 'suita_osm_378254301';
UPDATE buildings SET name = 'US1棟', latitude = 34.821123, longitude = 135.523492 WHERE id = 'suita_osm_378254579';
UPDATE buildings SET name = 'カフェテリア匠', latitude = 34.818148, longitude = 135.523766 WHERE id = 'suita_osm_389996267';
UPDATE buildings SET name = 'コンベンションセンター', latitude = 34.817881, longitude = 135.522586 WHERE id = 'suita_osm_379514489';
UPDATE buildings SET name = 'サイバーメディアセンター', latitude = 34.821711, longitude = 135.527035 WHERE id = 'suita_osm_435093454';
UPDATE buildings SET name = 'サイバーメディアセンター 吹田教育実習棟', latitude = 34.820854, longitude = 135.525865 WHERE id = 'suita_osm_378254567';
UPDATE buildings SET name = 'サイバーメディアセンター 本館', latitude = 34.822332, longitude = 135.526515 WHERE id = 'suita_osm_378254564';
UPDATE buildings SET name = 'スマートプロセス研究センター1号館', latitude = 34.824994, longitude = 135.525796 WHERE id = 'suita_osm_379513536';
UPDATE buildings SET name = 'スマートプロセス研究センター2号館', latitude = 34.824684, longitude = 135.525955 WHERE id = 'suita_osm_379513544';
UPDATE buildings SET name = 'たけのこ保育園', latitude = 34.819322, longitude = 135.522203 WHERE id = 'suita_osm_379514490';
UPDATE buildings SET name = 'テクノアライアンス棟', latitude = 34.820954, longitude = 135.522624 WHERE id = 'suita_osm_378255690';
UPDATE buildings SET name = 'ナノテクノロジー総合研究棟', latitude = 34.825763, longitude = 135.523536 WHERE id = 'suita_osm_379515971';
UPDATE buildings SET name = 'フォトニクスセンター・P3棟', latitude = 34.822677, longitude = 135.523632 WHERE id = 'suita_osm_378254307';
UPDATE buildings SET name = 'ポプラ通り福利会館', latitude = 34.818527, longitude = 135.522035 WHERE id = 'suita_osm_389996277';
UPDATE buildings SET name = 'まきば保育園', latitude = 34.821418, longitude = 135.527099 WHERE id = 'suita_osm_446898812';
UPDATE buildings SET name = 'レーザーエネルギー学研究センター', latitude = 34.820484, longitude = 135.524279 WHERE id = 'suita_osm_378412322';
UPDATE buildings SET name = '医学部', latitude = 34.819342, longitude = 135.526798 WHERE id = 'suita_osm_389996271';
UPDATE buildings SET name = '医学部付属病院', latitude = 34.819343, longitude = 135.52832 WHERE id = 'suita_osm_389996284';
UPDATE buildings SET name = '医学部保健学科/医学系研究科保健学専攻', latitude = 34.818151, longitude = 135.520616 WHERE id = 'suita_osm_379514193';
UPDATE buildings SET name = '核物理研AVFサイクロトロン棟', latitude = 34.826067, longitude = 135.527761 WHERE id = 'suita_osm_403002079';
UPDATE buildings SET name = '核物理研リングサイクロトロン棟', latitude = 34.82665, longitude = 135.527209 WHERE id = 'suita_osm_379513552';
UPDATE buildings SET name = '核物理研本館', latitude = 34.825942, longitude = 135.526799 WHERE id = 'suita_osm_379513540';
UPDATE buildings SET name = '環境安全研究管理センター', latitude = 34.819707, longitude = 135.524863 WHERE id = 'suita_osm_389996302';
UPDATE buildings SET name = '銀杏会館', latitude = 34.820904, longitude = 135.526716 WHERE id = 'suita_osm_378412320';
UPDATE buildings SET name = '工学AR棟', latitude = 34.822964, longitude = 135.524099 WHERE id = 'suita_osm_389996287';
UPDATE buildings SET name = '工学低温実験棟', latitude = 34.825284, longitude = 135.522958 WHERE id = 'suita_osm_403001239';
UPDATE buildings SET name = '工学部/工学研究科 A12棟', latitude = 34.825474, longitude = 135.525153 WHERE id = 'suita_osm_378258114';
UPDATE buildings SET name = '工学部/工学研究科 A13棟', latitude = 34.825719, longitude = 135.525833 WHERE id = 'suita_osm_378258112';
UPDATE buildings SET name = '工学部/工学研究科 A14棟', latitude = 34.825873, longitude = 135.525023 WHERE id = 'suita_osm_378258109';
UPDATE buildings SET name = '工学部/工学研究科 A15棟', latitude = 34.826093, longitude = 135.525544 WHERE id = 'suita_osm_378258107';
UPDATE buildings SET name = '工学部/工学研究科 R1棟', latitude = 34.823212, longitude = 135.521295 WHERE id = 'suita_osm_378255248';
UPDATE buildings SET name = '工学部/工学研究科 R2棟', latitude = 34.823415, longitude = 135.521417 WHERE id = 'suita_osm_378255247';
UPDATE buildings SET name = '工学部/工学研究科 R3棟', latitude = 34.823625, longitude = 135.521532 WHERE id = 'suita_osm_378258242';
UPDATE buildings SET name = '荒田記念館', latitude = 34.825158, longitude = 135.525777 WHERE id = 'suita_osm_379513534';
UPDATE buildings SET name = '産学共創A棟', latitude = 34.822973, longitude = 135.525016 WHERE id = 'suita_osm_389996289';
UPDATE buildings SET name = '産学共創B棟', latitude = 34.823205, longitude = 135.524757 WHERE id = 'suita_osm_389996288';
UPDATE buildings SET name = '産学共創C棟', latitude = 34.823361, longitude = 135.524287 WHERE id = 'suita_osm_389996286';
UPDATE buildings SET name = '産学共創D棟', latitude = 34.823522, longitude = 135.523883 WHERE id = 'suita_osm_378254306';
UPDATE buildings SET name = '産研コバルト棟', latitude = 34.824547, longitude = 135.524419 WHERE id = 'suita_osm_403001285';
UPDATE buildings SET name = '産研ライナック棟', latitude = 34.82473, longitude = 135.524621 WHERE id = 'suita_osm_389996297';
UPDATE buildings SET name = '産研管理棟', latitude = 34.824499, longitude = 135.523421 WHERE id = 'suita_osm_403001174';
UPDATE buildings SET name = '産研総合解析センター', latitude = 34.825092, longitude = 135.522289 WHERE id = 'suita_osm_389996300';
UPDATE buildings SET name = '産研第2研究棟', latitude = 34.825516, longitude = 135.52341 WHERE id = 'suita_osm_389996298';
UPDATE buildings SET name = '産研第一研究棟', latitude = 34.824794, longitude = 135.523385 WHERE id = 'suita_osm_378254559';
UPDATE buildings SET name = '産研電子プロセス実験棟', latitude = 34.825368, longitude = 135.522472 WHERE id = 'suita_osm_389996301';
UPDATE buildings SET name = '歯学部/歯学研究科', latitude = 34.819349, longitude = 135.521503 WHERE id = 'suita_osm_389996263';
UPDATE buildings SET name = '歯学部付属病院', latitude = 34.819563, longitude = 135.520968 WHERE id = 'suita_osm_389996265';
UPDATE buildings SET name = '社研A棟', latitude = 34.822941, longitude = 135.525756 WHERE id = 'suita_osm_403006524';
UPDATE buildings SET name = '社研B棟', latitude = 34.823139, longitude = 135.525604 WHERE id = 'suita_osm_378254565';
UPDATE buildings SET name = '情報科学研究科A棟', latitude = 34.818267, longitude = 135.522288 WHERE id = 'suita_osm_389996260';
UPDATE buildings SET name = '情報科学研究科B棟', latitude = 34.818003, longitude = 135.521749 WHERE id = 'suita_osm_389996261';
UPDATE buildings SET name = '情報科学研究科C棟', latitude = 34.818438, longitude = 135.52162 WHERE id = 'suita_osm_389996262';
UPDATE buildings SET name = '職員会館', latitude = 34.824754, longitude = 135.521721 WHERE id = 'suita_osm_378258248';
UPDATE buildings SET name = '人間科学部・人間科学研究科', latitude = 34.817818, longitude = 135.525918 WHERE id = 'suita_osm_446898800';
UPDATE buildings SET name = '吹田福利会館', latitude = 34.823284, longitude = 135.522076 WHERE id = 'suita_osm_378255691';
UPDATE buildings SET name = '生物工学国際交流センター', latitude = 34.824095, longitude = 135.520214 WHERE id = 'suita_osm_378258253';
UPDATE buildings SET name = '生命科学図書館', latitude = 34.818957, longitude = 135.525729 WHERE id = 'suita_osm_379514187';
UPDATE buildings SET name = '生命機能研究科 ES棟', latitude = 34.817206, longitude = 135.527838 WHERE id = 'suita_osm_389996282';
UPDATE buildings SET name = '生命機能研究科 ナノバイオロジー棟', latitude = 34.817408, longitude = 135.528364 WHERE id = 'suita_osm_389996283';
UPDATE buildings SET name = '生命機能研究科 細胞棟', latitude = 34.817496, longitude = 135.52751 WHERE id = 'suita_osm_389996280';
UPDATE buildings SET name = '生命機能研究科 生命システム棟', latitude = 34.817067, longitude = 135.52729 WHERE id = 'suita_osm_389996281';
UPDATE buildings SET name = '接合科学研究所', latitude = 34.825204, longitude = 135.526388 WHERE id = 'suita_osm_379513538';
UPDATE buildings SET name = '接合研実験棟', latitude = 34.824948, longitude = 135.526711 WHERE id = 'suita_osm_379513542';
UPDATE buildings SET name = '体育館', latitude = 34.817592, longitude = 135.523132 WHERE id = 'suita_osm_378254214';
UPDATE buildings SET name = '大阪大学 国際交流会館吹田分館', latitude = 34.824431, longitude = 135.51829 WHERE id = 'suita_osm_505704346';
UPDATE buildings SET name = '大阪大学歯学部', latitude = 34.818831, longitude = 135.521164 WHERE id = 'suita_osm_389996264';
UPDATE buildings SET name = '大阪大学本部', latitude = 34.818698, longitude = 135.523905 WHERE id = 'suita_osm_389996266';
UPDATE buildings SET name = '蛋白研NMR実験棟', latitude = 34.825492, longitude = 135.519652 WHERE id = 'suita_osm_403002811';
UPDATE buildings SET name = '蛋白研共同研究拠点', latitude = 34.825736, longitude = 135.520139 WHERE id = 'suita_osm_379516456';
UPDATE buildings SET name = '蛋白研構造解析研究棟', latitude = 34.825338, longitude = 135.519383 WHERE id = 'suita_osm_379516459';
UPDATE buildings SET name = '蛋白研分析実験棟', latitude = 34.825577, longitude = 135.520423 WHERE id = 'suita_osm_379516457';
UPDATE buildings SET name = '蛋白質研究所', latitude = 34.825332, longitude = 135.520121 WHERE id = 'suita_osm_379516458';
UPDATE buildings SET name = '中央機械棟', latitude = 34.823838, longitude = 135.522364 WHERE id = 'suita_osm_378255936';
UPDATE buildings SET name = '超高圧電子顕微鏡センター', latitude = 34.823716, longitude = 135.52508 WHERE id = 'suita_osm_378254561';
UPDATE buildings SET name = '超電導フォトニクス実験棟', latitude = 34.823328, longitude = 135.523858 WHERE id = 'suita_osm_403006709';
UPDATE buildings SET name = '低温センター', latitude = 34.823367, longitude = 135.523532 WHERE id = 'suita_osm_378254305';
UPDATE buildings SET name = '電子顕微鏡センター', latitude = 34.81875, longitude = 135.523147 WHERE id = 'suita_osm_389996268';
UPDATE buildings SET name = '楠本会館', latitude = 34.825337, longitude = 135.521598 WHERE id = 'suita_osm_389996299';
UPDATE buildings SET name = '微研南館', latitude = 34.823801, longitude = 135.519441 WHERE id = 'suita_osm_403003008';
UPDATE buildings SET name = '微研北館', latitude = 34.825144, longitude = 135.518876 WHERE id = 'suita_osm_389996294';
UPDATE buildings SET name = '微研本館', latitude = 34.824124, longitude = 135.519157 WHERE id = 'suita_osm_389996291';
UPDATE buildings SET name = '保健センター 吹田分室', latitude = 34.821277, longitude = 135.52548 WHERE id = 'suita_osm_378254566';
UPDATE buildings SET name = '本部前福利会館', latitude = 34.819227, longitude = 135.524766 WHERE id = 'suita_osm_389996305';
UPDATE buildings SET name = '免疫学フロンティア研究センター', latitude = 34.824805, longitude = 135.519897 WHERE id = 'suita_osm_389996293';
UPDATE buildings SET name = '薬学部/薬学研究科', latitude = 34.817065, longitude = 135.520699 WHERE id = 'suita_osm_389996274';
UPDATE buildings SET name = '融合型生命科学総合研究棟', latitude = 34.824406, longitude = 135.519771 WHERE id = 'suita_osm_403003007';
UPDATE buildings SET name = '理工学図書館', latitude = 34.822189, longitude = 135.523098 WHERE id = 'suita_osm_378253856';
UPDATE buildings SET name = 'グローバルコラボレーションセンター', latitude = 34.806442, longitude = 135.453897 WHERE id = 'toyonaka_osm_225710187';
UPDATE buildings SET name = 'サイバーメディアセンター', latitude = 34.805051, longitude = 135.455962 WHERE id = 'toyonaka_osm_220488371';
UPDATE buildings SET name = 'まちかね保育園', latitude = 34.804576, longitude = 135.456808 WHERE id = 'toyonaka_osm_462745564';
UPDATE buildings SET name = 'らふぉれ', latitude = 34.803399, longitude = 135.453931 WHERE id = 'toyonaka_osm_158629518';
UPDATE buildings SET name = 'ルネクール・ムラタ', latitude = 34.807522, longitude = 135.45494 WHERE id = 'toyonaka_osm_498412575';
UPDATE buildings SET name = '学生交流棟', latitude = 34.805687, longitude = 135.45275 WHERE id = 'toyonaka_osm_157287063';
UPDATE buildings SET name = '基礎工学部G棟', latitude = 34.803374, longitude = 135.45691 WHERE id = 'toyonaka_osm_84971080';
UPDATE buildings SET name = '基礎工学部J棟', latitude = 34.803219, longitude = 135.456283 WHERE id = 'toyonaka_osm_84971156';
UPDATE buildings SET name = '基礎工学部国際棟 (Σホール)', latitude = 34.803435, longitude = 135.455335 WHERE id = 'toyonaka_osm_229128016';
UPDATE buildings SET name = '共通教育A棟', latitude = 34.806164, longitude = 135.454339 WHERE id = 'toyonaka_osm_225710189';
UPDATE buildings SET name = '共通教育B棟', latitude = 34.805899, longitude = 135.454865 WHERE id = 'toyonaka_osm_225710190';
UPDATE buildings SET name = '共通教育C棟', latitude = 34.806413, longitude = 135.45472 WHERE id = 'toyonaka_osm_225710191';
UPDATE buildings SET name = '健康体育研究棟', latitude = 34.807107, longitude = 135.456037 WHERE id = 'toyonaka_osm_463870353';
UPDATE buildings SET name = '言語文化研究科', latitude = 34.805466, longitude = 135.453569 WHERE id = 'toyonaka_osm_158629520';
UPDATE buildings SET name = '実験棟', latitude = 34.806334, longitude = 135.453491 WHERE id = 'toyonaka_osm_225705867';
UPDATE buildings SET name = '総合学術博物館', latitude = 34.807422, longitude = 135.449044 WHERE id = 'toyonaka_osm_225710186';
UPDATE buildings SET name = '総合図書館', latitude = 34.804954, longitude = 135.45507 WHERE id = 'toyonaka_osm_157098221';
UPDATE buildings SET name = '多目的倉庫', latitude = 34.8069, longitude = 135.455699 WHERE id = 'toyonaka_osm_463870354';
UPDATE buildings SET name = '体育館', latitude = 34.807009, longitude = 135.455258 WHERE id = 'toyonaka_osm_311504482';
UPDATE buildings SET name = '待兼山会館', latitude = 34.805111, longitude = 135.452112 WHERE id = 'toyonaka_osm_229130610';
UPDATE buildings SET name = '大講義棟', latitude = 34.805716, longitude = 135.455191 WHERE id = 'toyonaka_osm_463870348';
UPDATE buildings SET name = '大阪大学会館', latitude = 34.806669, longitude = 135.452583 WHERE id = 'toyonaka_osm_225710182';
UPDATE buildings SET name = '大阪大学国際交流会館', latitude = 34.805204, longitude = 135.457177 WHERE id = 'toyonaka_osm_157105371';
UPDATE buildings SET name = '大阪大学生協', latitude = 34.804461, longitude = 135.452863 WHERE id = 'toyonaka_osm_157119834';
UPDATE buildings SET name = '第二体育館', latitude = 34.80723, longitude = 135.455779 WHERE id = 'toyonaka_osm_463870352';
UPDATE buildings SET name = '中庭会議室', latitude = 34.804744, longitude = 135.454427 WHERE id = 'toyonaka_osm_229237337';
UPDATE buildings SET name = '日本学棟', latitude = 34.804859, longitude = 135.453402 WHERE id = 'toyonaka_osm_157302297';
UPDATE buildings SET name = '美学棟', latitude = 34.80468, longitude = 135.453696 WHERE id = 'toyonaka_osm_157294755';
UPDATE buildings SET name = '文法経講義棟', latitude = 34.805107, longitude = 135.453469 WHERE id = 'toyonaka_osm_157294754';
UPDATE buildings SET name = '文法経本館', latitude = 34.804738, longitude = 135.454463 WHERE id = 'toyonaka_osm_157146925';
UPDATE buildings SET name = '法経講義棟', latitude = 34.805013, longitude = 135.453788 WHERE id = 'toyonaka_osm_157294753';
UPDATE buildings SET name = '豊中共創棟A', latitude = 34.802853, longitude = 135.456244 WHERE id = 'toyonaka_osm_311504481';
UPDATE buildings SET name = '豊中共創棟B', latitude = 34.802932, longitude = 135.455897 WHERE id = 'toyonaka_osm_1525493177';
UPDATE buildings SET name = '豊中総合学館', latitude = 34.80428, longitude = 135.453748 WHERE id = 'toyonaka_osm_229126801';
UPDATE buildings SET name = '明道館', latitude = 34.804575, longitude = 135.452525 WHERE id = 'toyonaka_osm_383575495';
UPDATE buildings SET name = '理学部A棟', latitude = 34.802603, longitude = 135.454957 WHERE id = 'toyonaka_osm_461654531';
UPDATE buildings SET name = '理学部B棟', latitude = 34.802662, longitude = 135.455635 WHERE id = 'toyonaka_osm_461654532';
UPDATE buildings SET name = '理学部C棟', latitude = 34.802263, longitude = 135.455476 WHERE id = 'toyonaka_osm_461654533';
UPDATE buildings SET name = '理学部D棟', latitude = 34.802453, longitude = 135.455605 WHERE id = 'toyonaka_osm_461654535';
UPDATE buildings SET name = '理学部E棟', latitude = 34.802401, longitude = 135.45625 WHERE id = 'toyonaka_osm_461654534';
UPDATE buildings SET name = '理学部F棟', latitude = 34.801731, longitude = 135.45511 WHERE id = 'toyonaka_osm_231162027';
UPDATE buildings SET name = '理学部G棟', latitude = 34.801829, longitude = 135.455571 WHERE id = 'toyonaka_osm_231162028';
UPDATE buildings SET name = '理学部H棟', latitude = 34.802102, longitude = 135.455092 WHERE id = 'toyonaka_osm_461654530';
UPDATE buildings SET name = '理学部J棟', latitude = 34.80298, longitude = 135.455668 WHERE id = 'toyonaka_osm_486946397';
